\c colorful_characters_dev

INSERT INTO characters (name, image, description, protagonist, playable, lgbt, lgbt_type, poc, poc_type, game) VALUES 
('Zevran Arainai', 'https://static.wikia.nocookie.net/dragonage/images/3/3b/Zevran_the_Crow.jpg/revision/latest?cb=20120813013338', 'Zevran is an elven rogue that can potentially become a party member. He is also one of the two romance options that the player character can enter into a relationship with whether the player character is male or female.', false, true, true, 'Bisexual', false, NULL, 'Dragon Age Origins'),
('The Warden', 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS24uCXKaQcFwe5DWCGYzfagSNHJF0TP1QD5sLKhAzR112HQohj', 'The main character of Dragon Age Origins. With the completely customizable appearance and the option of romancing 4 different characters, 2 male and 2 female, the player can have a character that fits them better.', true, true, true, 'Customizable', false, NULL, 'Dragon Age Origins'),
('Concord', 'https://assets.nintendo.com/image/upload/f_auto/q_auto/dpr_2.0/c_scale,w_400/ncom/en_US/games/switch/g/garden-story-switch/description-image', 'Concord is a grape and the main character of Garden Story. Though Concord doesnt talk much, the villagers you help throughout the game refer to Concord with they/them pronouns. It''s their job to protect many villages from the growing threat of Rot', true, true, true, 'Gender Neutral', false, NULL, 'Garden Story'),
('Akito Izuki', 'https://images.ctfassets.net/rporu91m20dc/4SbQvsNgslpLvNepUX6uzs/3d70198125baeeef92e49ba35907039b/GWT_Akito_HERO_1920x870.png', 'Akito is the main character of Ghostwire Tokyo. Teaming up with a spirit, he must find defeat the man that kidnapped his sister, and caused the cities population to vanish.', true, true, false, NULL, true, 'Japanese', 'Ghostwire Tokyo'),
('Colt Vahn', 'https://pbs.twimg.com/media/FN6Ab1BXIAsK2iB.jpg:large', 'Colt is the main character of Deathloop. He is trapped in a timeloop on an island, with no memories. In order to escape, he must uncover his past and take down the people that caused the loop.', true, true, true, 'Bisexual', true, 'African American', 'Deathloop'),
('Juliana Blake', 'https://pbs.twimg.com/media/E_LxVl8WQAI15dH.jpg:large', 'Julianna is the main antagonist and secondary playable character of Deathloop. Her main goal is to stop Colt from breaking the timeloop surrounding the island by killing him over and over again.', false, true, false, NULL, true, 'African American', 'Deathloop');
-- ('', '', '', true, true, true, NULL, false, NULL, ''),
-- (name, image, description, protagonist, playable, lgbt, lgbt_type, poc, poc_type, game) 